package fr.istic.mob.stareg.database.modeles;


import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import fr.istic.mob.stareg.database.StarContract;

/**
 * trip Table.
 * @Author Bonaventure Gbehe - Rebecca Ehua
 */
@Entity(tableName = StarContract.Trips.CONTENT_PATH)
public class TripEntity {

    @NonNull
    @PrimaryKey
    private String _id;

    @ColumnInfo(name = StarContract.Trips.TripColumns.ROUTE_ID)
    private String route_id;

    @ColumnInfo(name = StarContract.Trips.TripColumns.SERVICE_ID)
    private String service_id;

    @ColumnInfo(name = StarContract.Trips.TripColumns.HEADSIGN)
    private String trip_headsign;

    @ColumnInfo(name = StarContract.Trips.TripColumns.DIRECTION_ID)
    private String direction_id;

    @ColumnInfo(name = StarContract.Trips.TripColumns.BLOCK_ID)
    private String block_id;

    @ColumnInfo(name = StarContract.Trips.TripColumns.WHEELCHAIR_ACCESSIBLE)
    private String wheelchair_accessible;

    /**
     * Constructor.
     *
     * @param _id                   autogenerated identifier
     * @param route_id              identifier of the bus line
     * @param service_id            identifier of the service
     * @param trip_headsign         headsign of the trip
     * @param direction_id          0 or 1
     * @param block_id
     * @param wheelchair_accessible 0 or 1
     */
    public TripEntity(@NonNull String _id, String route_id, String service_id, String trip_headsign, String direction_id, String block_id, String wheelchair_accessible) {
        this.route_id = route_id;
        this.service_id = service_id;
        this._id = _id;
        this.trip_headsign = trip_headsign;
        this.direction_id = direction_id;
        this.block_id = block_id;
        this.wheelchair_accessible = wheelchair_accessible;
    }

    /**
     * @return identifier of the route
     */
    public String getRoute_id() {
        return route_id;
    }

    /**
     * Sets the identifier of the route.
     *
     * @param route_id new identifier
     */
    public void setRoute_id(String route_id) {
        this.route_id = route_id;
    }

    /**
     * @return identifier of the service
     */
    public String getService_id() {
        return service_id;
    }

    /**
     * Sets the identifier of the service.
     *
     * @param service_id new identifier
     */
    public void setService_id(String service_id) {
        this.service_id = service_id;
    }

    /**
     * @return autogenerated identifier
     */
    public String get_id() {
        return _id;
    }

    /**
     * Sets the identifier.
     *
     * @param id new identifier
     */
    public void set_id(String id) {
        this._id = _id;
    }

    /**
     * Sets the direction.
     *
     * @param direction_id new direction (0 or 1)
     */
    public void setDirection_id(String direction_id) {
        this.direction_id = direction_id;
    }

    /**
     * @return identifier of the block
     */
    public String getBlock_id() {
        return block_id;
    }

    /**
     * Sets the identifier of the block.
     *
     * @param block_id new identifier
     */
    public void setBlock_id(String block_id) {
        this.block_id = block_id;
    }

    /**
     * @return trip's headsign.
     */
    public String getTrip_headsign() {
        return trip_headsign;
    }

    /**
     * Sets trip's headsign
     *
     * @param trip_headsign new headsign
     */
    public void setTrip_headsign(String trip_headsign) {
        this.trip_headsign = trip_headsign;
    }

    /**
     * @return 0 or 1, the direction
     */
    public String getDirection_id() {
        return direction_id;
    }

    /**
     * @return 0 if not accessible 1 otherwise
     */
    public String getWheelchair_accessible() {
        return wheelchair_accessible;
    }

    /**
     * Sets wheelchair_accessible.
     *
     * @param wheelchair_accessible new value
     */
    public void setWheelchair_accessible(String wheelchair_accessible) {
        this.wheelchair_accessible = wheelchair_accessible;
    }
}

